# Generated by Django 4.1.1 on 2022-09-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_slug_tag_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='url',
        ),
    ]
