# Generated by Django 4.1.1 on 2022-09-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_url_post_oid_rename_url_tag_oid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='oid',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='oid',
        ),
        migrations.AddField(
            model_name='post',
            name='instance_id',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='instance_id',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
